#!/bin/bash

# Create the directory /tmp/regataos-prime
if test -e /tmp/regataos-prime ; then
	cd /tmp/
	chmod 777 regataos-prime
else
	cd /tmp/
	mkdir -p regataos-prime
	chmod 777 regataos-prime
fi

# Check for hybrid graphics support
#Identify dGPU
kmsg=$(inxi -G | grep Card-2)

if [[ $kmsg == *"AMD"* ]]; then
	echo "Hybrid graphics detected"
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	echo AMD > /tmp/regataos-prime/use-hybrid-graphics-amd.txt
	rm -f "/tmp/regataos-prime/use-hybrid-graphics-nvidia.txt"
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"
	rm -f "/tmp/regataos-prime/nvidia-driver.txt"

elif [[ $kmsg == *"Radeon"* ]]; then
	echo "Hybrid graphics detected"
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	echo AMD > /tmp/regataos-prime/use-hybrid-graphics-amd.txt
	rm -f "/tmp/regataos-prime/use-hybrid-graphics-nvidia.txt"
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"
	rm -f "/tmp/regataos-prime/nvidia-driver.txt"

elif [[ $kmsg == *"ATI"* ]]; then
	echo "Hybrid graphics detected"
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	echo AMD > /tmp/regataos-prime/use-hybrid-graphics-amd.txt
	rm -f "/tmp/regataos-prime/use-hybrid-graphics-nvidia.txt"
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"
	rm -f "/tmp/regataos-prime/nvidia-driver.txt"

elif [[ $kmsg == *"NVIDIA"* ]]; then
	echo "Hybrid graphics detected"
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	echo NVIDIA > /tmp/regataos-prime/use-hybrid-graphics-nvidia.txt
	echo NVIDIA > /tmp/regataos-prime/nvidia-driver.txt
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"
	rm -f "/tmp/regataos-prime/use-hybrid-graphics-amd.txt"

	# Check nvidia driver
	kmsg2=$(lshw -class display | grep "driver")
	if [[ $kmsg2 == *"nvidia"* ]]; then

		# If you are in Regata OS, remove some settings from X.Org Server
		kmsg=$(grep -r NAME /etc/os-release)
		if [[ $kmsg == *"Regata OS"* ]]; then
			rm -f "/etc/X11/xorg.conf.d/20-amdgpu.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-amdgpu.conf"
			rm -f "/etc/X11/xorg.conf.d/20-radeon.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-radeon.conf"
			rm -f "/etc/X11/xorg.conf.d/20-intel.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-intel.conf"
			rm -f "/etc/X11/xorg.conf.d/20-nvidia.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-nvidia.conf"
		fi

		# Copy xorg config files
		if test -e /usr/bin/nvidia-xconfig ; then
			cp -f /opt/regataos-prime/all-files/10-intel-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-intel-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-amdgpu-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-amdgpu-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-intel-nvidia-drm-outputclass.conf /etc/X11/xorg.conf.d/10-intel-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-amdgpu-nvidia-drm-outputclass.conf /etc/X11/xorg.conf.d/10-amdgpu-nvidia-drm-outputclass.conf
		fi
	fi

elif [[ $kmsg == *"GeForce"* ]]; then
	echo "Hybrid graphics detected"
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	echo NVIDIA > /tmp/regataos-prime/use-hybrid-graphics-nvidia.txt
	echo NVIDIA > /tmp/regataos-prime/nvidia-driver.txt
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"
	rm -f "/tmp/regataos-prime/use-hybrid-graphics-amd.txt"

	# Check nvidia driver
	kmsg2=$(lshw -class display | grep "driver")
	if [[ $kmsg2 == *"nvidia"* ]]; then

		# If you are in Regata OS, remove some settings from X.Org Server
		kmsg=$(grep -r NAME /etc/os-release)
		if [[ $kmsg == *"Regata OS"* ]]; then
			rm -f "/etc/X11/xorg.conf.d/20-amdgpu.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-amdgpu.conf"
			rm -f "/etc/X11/xorg.conf.d/20-radeon.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-radeon.conf"
			rm -f "/etc/X11/xorg.conf.d/20-intel.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-intel.conf"
			rm -f "/etc/X11/xorg.conf.d/20-nvidia.conf"
			rm -f "/usr/share/X11/xorg.conf.d/20-nvidia.conf"
		fi

		# Copy xorg config files
		if test -e /usr/bin/nvidia-xconfig ; then
			cp -f /opt/regataos-prime/all-files/10-intel-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-intel-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-amdgpu-nvidia-drm-outputclass.conf /usr/share/X11/xorg.conf.d/10-amdgpu-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-intel-nvidia-drm-outputclass.conf /etc/X11/xorg.conf.d/10-intel-nvidia-drm-outputclass.conf
			cp -f /opt/regataos-prime/all-files/10-amdgpu-nvidia-drm-outputclass.conf /etc/X11/xorg.conf.d/10-amdgpu-nvidia-drm-outputclass.conf
		fi
	fi

else
	echo "Not detected graphics"
	echo Not use hybrid graphics > /tmp/regataos-prime/not-hybrid-graphics.txt
	rm -f "/tmp/regataos-prime/use-hybrid-graphics.txt"
fi

# Check for hybrid graphics support
if test -e /tmp/regataos-prime/use-hybrid-graphics.txt ; then
	# Open apps with hybrid graphics manually
	cp -f /opt/regataos-prime/all-files/prime-gpu.desktop /usr/share/kservices5/ServiceMenus/prime-gpu.desktop

	# Create .desktop file for prime settings
	cp -f /opt/regataos-prime/all-files/prime-settings.desktop /usr/share/applications/prime-settings.desktop

	# Run script with supported apps whitelist
	sh /opt/regataos-prime/scripts/apps-hybrid-graphics

	#Collect hardware information for PRIME Settings
	sh /opt/regataos-prime/scripts/prime-settings-system-info.sh

elif test -e /tmp/regataos-prime/not-hybrid-graphics.txt ; then
	# Remove .desktop file for prime settings
	rm -f "/usr/share/kservices5/ServiceMenus/prime-gpu.desktop"
	rm -f "/usr/share/applications/prime-settings.desktop"

else
	echo "Settings not detected"
fi
