#!/bin/bash

if test -e /tmp/regataos-prime/nvidia-driver.txt ; then
	regataos-dgpu vkcube
else
	GALLIUM_HUD_PERIOD=1 GALLIUM_HUD="simple,GPU-load,VRAM-usage,memory-clock,shader-clock,cpu,temperature,fps" regataos-dgpu glxgears
fi
