#!/bin/bash

case $1 in
   "-gl") GALLIUM_HUD_PERIOD=1 GALLIUM_HUD="simple,GPU-load,VRAM-usage,memory-clock,shader-clock,cpu,temperature,fps" regataos-dgpu glxgears
         ;;
   "-vk") regataos-dgpu vkcube
         ;;
   *) echo "Invalid option!"
      exit 1
      ;;
esac
