#!/bin/bash
#

rm -f "/opt/magma/regataosprime"
rm -f "/usr/bin/regataosprime"
rm -f "/usr/share/kservices5/ServiceMenus/prime-gpu.desktop"
rm -f "/usr/share/applications/prime-settings.desktop"
rm -f "/usr/bin/prime-dgpu"

systemctl stop    detect-hybrid-graphics.service || true
systemctl disable detect-hybrid-graphics.service || true

systemctl stop    regataos-check-use-dgpu.service || true
systemctl disable regataos-check-use-dgpu.service || true

systemctl stop    apps-hybrid-graphics-service.service || true
systemctl disable apps-hybrid-graphics-service.service || true

update-desktop-database
