#!/bin/bash
#

# Fix permission for sudoers-prime-settings file
chown root:root /etc/sudoers.d/sudoers-prime-settings
chmod 600 /etc/sudoers.d/sudoers-prime-settings

# Create the directory /tmp/regataos-prime
if test -e /tmp/regataos-prime ; then
	cd /tmp/
	chmod 777 regataos-prime
else
	cd /tmp/
	mkdir -p regataos-prime
	chmod 777 regataos-prime
fi

# Create regataosprime executable
if test -e /opt/magma/regataosprime ; then
	echo "OK"
else
	cp -f /opt/magma/magma /opt/magma/regataosprime
fi

if test -e /usr/bin/regataosprime ; then
	echo "OK"
else
	ln -s /opt/magma/regataosprime /usr/bin/regataosprime
fi

if test -e /usr/bin/prime-dgpu ; then
	echo "OK"
else
	ln -s /usr/bin/regataos-dgpu /usr/bin/prime-dgpu
fi

# Start systemd service
systemctl enable  detect-hybrid-graphics.service || true
systemctl start   detect-hybrid-graphics.service || true
systemctl restart detect-hybrid-graphics.service || true

systemctl enable  check-use-dgpu.service || true
systemctl start   check-use-dgpu.service || true
systemctl restart check-use-dgpu.service || true

# Update icons
update-desktop-database
