#!/bin/bash
#

# Remove files created during installation
rm -f "/opt/magma/regataosprime"
rm -f "/usr/bin/regataosprime"
rm -f "/usr/bin/prime-dgpu"

# Start systemd service
systemctl stop    detect-hybrid-graphics.service || true
systemctl disable detect-hybrid-graphics.service || true

systemctl stop    check-use-dgpu.service || true
systemctl disable check-use-dgpu.service || true

# Update icons
update-desktop-database
