#!/bin/bash

# Clear cache
rm -f "/tmp/regataos-prime/use-hybrid-graphics-nvidia.txt"
rm -f "/tmp/regataos-prime/use-hybrid-graphics-amd.txt"

# Fix for files folder
if test -e /tmp/regataos-prime ; then
	cd /tmp/
	chmod 777 regataos-prime
else
	cd /tmp/
	mkdir -p regataos-prime
	chmod 777 regataos-prime
fi

# Check for hybrid graphics
kmsg=$(xrandr --listproviders | grep Providers:)
echo $kmsg

xrandr --setprovideroffloadsink 1 0

if [[ $kmsg == *"2"* ]]; then

	echo "Hybrid graphics detected."
	echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
	rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"

	xrandr --setprovideroffloadsink 1 0

elif [[ $kmsg == *"1"* ]]; then

	sudo /usr/share/regataos/gpu/prime/check-gpus.sh start

	kmsg2=$(grep display /tmp/regataos-prime/display.txt | wc -l)
	echo $kmsg2

	if [[ $kmsg2 -ge 2 ]]; then
		echo "Hybrid graphics detected."
		echo Set hybrid graphics > /tmp/regataos-prime/use-hybrid-graphics.txt
		rm -f "/tmp/regataos-prime/not-hybrid-graphics.txt"

		xrandr --setprovideroffloadsink 1 0
	else
		echo "There seems to be no hybrid graphics."
		echo Not use hybrid graphics > /tmp/regataos-prime/not-hybrid-graphics.txt
		rm -f "/tmp/regataos-prime/use-hybrid-graphics.txt"
	fi

else

	echo "No graphs detected."
	echo Not use hybrid graphics > /tmp/regataos-prime/not-hybrid-graphics.txt
	rm -f "/tmp/regataos-prime/use-hybrid-graphics.txt"

fi
