#!/bin/bash
# Xsetup - run as root before the login dialog appears

# Enable/Desable Reverse Prime
if test -e /tmp/regataos-prime/reverse-prime.txt ; then
	if test -e /tmp/regataos-prime/renderer-dgpu.txt ; then
		xrandr --setprovideroutputsource 0 1
		xrandr --auto
		xrandr --dpi 96
	else
		xrandr --auto
		xrandr --dpi 96
	fi
fi
